### ISSUE TITLE
Closing moving curtains causes error and state inconsistency

### ISSUE THREAD

**Issue by dnicolson** [SwitchBot/homebridge-switchbot-ble#12]
1. Open the curtains
2. Close the curtains while they're opening

The curtains finish opening but an error is logged and the HomeKit state is closed while the curtains are open.

homebridge-switchbot-ble v1.2.1
Firmware v2.8

```
[11/18/2020, 17:55:58] [SwitchBotPlatform] WoCurtain xx:xx:xx:xx:xx:xx
[11/18/2020, 17:55:58] [SwitchBotPlatform] WoCurtain yy:yy:yy:yy:yy:yy
[11/18/2020, 17:55:58] [SwitchBotPlatform] WoCurtain (yy:yy:yy:yy:yy:yy) was found.
[11/18/2020, 17:55:58] [SwitchBotPlatform] The Curtain is moving...
[11/18/2020, 17:55:59] [SwitchBotPlatform] Done.
[11/18/2020, 17:55:59] [SwitchBotPlatform] Target position of the Curtain has been set to: 100%
[11/18/2020, 17:56:32] [SwitchBotPlatform] Target position of the Curtain setting: 0%
[11/18/2020, 17:56:34] [SwitchBotPlatform] Scan done.
[11/18/2020, 17:56:34] [SwitchBotPlatform] WoCurtain xx:xx:xx:xx:xx:xx
[11/18/2020, 17:56:34] [SwitchBotPlatform] WoCurtain yy:yy:yy:yy:yy:yy
[11/18/2020, 17:56:34] [SwitchBotPlatform] WoCurtain (yy:yy:yy:yy:yy:yy) was found.
[11/18/2020, 17:56:34] [SwitchBotPlatform] The Curtain is moving...
[11/18/2020, 17:56:35] [SwitchBotPlatform] Done.
[11/18/2020, 17:56:35] [SwitchBotPlatform] Target position of the Curtain has been set to: 0%
[11/18/2020, 17:56:39] [SwitchBotPlatform] Target position of the Curtain setting: 100%
[11/18/2020, 17:56:41] [SwitchBotPlatform] Scan done.
[11/18/2020, 17:56:41] [SwitchBotPlatform] WoCurtain yy:yy:yy:yy:yy:yy
[11/18/2020, 17:56:41] [SwitchBotPlatform] WoCurtain (yy:yy:yy:yy:yy:yy) was found.
[11/18/2020, 17:56:41] [SwitchBotPlatform] The Curtain is moving...
[11/18/2020, 17:56:42] [SwitchBotPlatform] Error: Failed to discover services and characteristics: DISCONNECTED
    at SwitchbotDeviceWoCurtain._ondisconnect_internal (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:161:16)
    at Peripheral.<anonymous> (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:122:14)
    at Object.onceWrapper (events.js:417:28)
    at Peripheral.emit (events.js:311:20)
    at Noble.onDisconnect (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/noble.js:224:16)
    at NobleBindings.emit (events.js:311:20)
    at NobleBindings.onDisconnComplete (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:260:10)
    at Hci.emit (events.js:311:20)
    at Hci.onSocketData (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:447:12)
    at BluetoothHciSocket.emit (events.js:311:20)

[11/18/2020, 17:56:42] [SwitchBotPlatform] Target position of the Curtain setting failed!
```

**Comment by SwitchBot-Wonderlabs** [comment]
Hi, @dnicolson , try the new version V1.2.2.

**Comment by dnicolson** [comment]
Both issues are fixed, thanks!
